# Generated by Django 5.1.4 on 2024-12-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conn', '0007_delete_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='participants_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
