# Generated by Django 5.1.4 on 2024-12-26 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conn', '0008_alter_chatroom_participants_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweetusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('set_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='host',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Host_chatroom', to='conn.sweetusers'),
        ),
    ]
