# Generated by Django 5.1.4 on 2024-12-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conn', '0009_sweetusers_remove_chatroom_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweetusers',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
