services:
  redis:
    image: redis:alpine  # Use a lightweight Redis image
    ports:
      - "6379:6379"
  app:
    build: .
    volumes :
      - .:/chatapp
    ports:
      [8000:8000]
    image: app:chatapp
    container_name: chat_container
    environment:
      - DJANGO_ENV=local
    command:  [./entrypoint.sh]
    depends_on:
      - redis
      - db
  db:
    image: postgres
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db 